version: '3'
services:
  web:
    build: .
    ports:
      - 8000:3000
    volumes:
      - ./teste-portainer:/app
    stdin_open: true
    tty: true
    networks:
      - teste-portainer

networks:
  teste-portainer:
    external: false